### ISSUE TITLE
Store ASCII code of characters instead of word

### ISSUE THREAD

**Issue by mjodeh** [davedoesdev/qlobber#18] opened 2020-06-18 03:51 UTC
HI @davedoesdev 
Have you considered storing the ASCII code of the pattern instead of using `Map` type in ur Trie. do you think it would give a better performance in terms of add and match?
[example](https://miro.medium.com/max/1000/1*sZOrNXzlQICVv5ePpav1-g.jpeg)

**Comment by davedoesdev** [comment] 2020-06-18 06:38
Hi @mjodeh 
Thanks for your suggestion, let's explore it a little. What would you use instead of `Map` when looking up words?

**Comment by mjodeh** [comment] 2020-06-18 13:32
right now in trie code `Map` type is being used, in which the whole word is stored and the check goes with checking is the key exists or not.
What I'm suggesting here is to use an array to store the allowed characters (alpha numeric) with the separators (*, #), then there will be no need to split the input, the insertion and matching will have the same complexity, also the backtrack will be there by default.
take a look at this [Article](https://medium.com/basecs/trying-to-understand-tries-3ec6bede0014)
I've read the [reabbit mq](https://www.rabbitmq.com/blog/2010/09/14/very-fast-and-scalable-topic-routing-part-1/) in which they implemented it `word by word` which becomes string comparison which is in general a time consuming and cpu some what intensive compared to char comparison.
what do u think? also it won't take more memory

**Comment by davedoesdev** [comment] 2020-06-18 20:25
I wondering how the wildcards would work. Since they match on whole words, we'd need to scan through to find the separators (`.`).

**Comment by mjodeh** [comment] 2020-06-19 02:22
the separator and wild cards will be added to the trie

> What I'm suggesting here is to use an array to store the allowed characters (alpha numeric) with the separators (*, #), then there will be no need to split the input, the insertion and matching will have the same complexity

**Comment by mjodeh** [comment] 2020-06-19 02:24
do you think that if it was implemented in C it would have a better performance?

**Comment by mjodeh** [comment] 2020-06-19 02:32
this is an example https://github.com/frncscccvl/trie/blob/master/Trie.c
a flag could be added isWord to the child to indicate a complete word if we don't want to store the seperator

**Comment by davedoesdev** [comment] 2020-06-19 07:04
A native version is available here: https://github.com/davedoesdev/qlobber/tree/master/native

Currently this integrates with Node with support worker threads. However, the class hierarchy should be generic enough to use in other projects.

Your idea is interesting but unfortunately I don't have time to pursue it right now :disappointed:. The wildcard matching algorithm would definitely need reworking.

**Comment by davedoesdev** [comment] 2020-06-19 07:12
The other thing worth considering is that V8 does a lot of optimisation for `Map`: https://stackoverflow.com/questions/33611509/es6-map-and-set-complexity-v8-implementation has some links.

**Comment by davedoesdev** [comment] 2020-09-01 04:27
OK, for _non-wildcard_ matches, a character-based trie is faster than a `Map`-based trie.

Character-based trie (`character-trie` branch):

```
  add x20,000
  ┌─────────┬────────────┬──────────────┬──────────┐
  │         │ total (ms) │ average (ns) │ diff (%) │
  ├─────────┼────────────┼──────────────┼──────────┤
  │ default │      1,666 │       83,322 │        - │
  │ dedup   │      1,747 │       87,354 │        5 │
  └─────────┴────────────┴──────────────┴──────────┘

  match x20,000
  ┌─────────┬────────────┬──────────────┬──────────┐
  │         │ total (ms) │ average (ns) │ diff (%) │
  ├─────────┼────────────┼──────────────┼──────────┤
  │ dedup   │        113 │        5,631 │        - │
  │ default │        147 │        7,347 │       30 │
  └─────────┴────────────┴──────────────┴──────────┘
```

For `Map`-based trie (`no-wildcards-in-bench` branch):

```
  add x20,000
  ┌─────────┬────────────┬──────────────┬──────────┐
  │         │ total (ms) │ average (ns) │ diff (%) │
  ├─────────┼────────────┼──────────────┼──────────┤
  │ dedup   │      1,909 │       95,461 │        - │
  │ default │      1,926 │       96,323 │        1 │
  └─────────┴────────────┴──────────────┴──────────┘

  match x20,000
  ┌─────────┬────────────┬──────────────┬──────────┐
  │         │ total (ms) │ average (ns) │ diff (%) │
  ├─────────┼────────────┼──────────────┼──────────┤
  │ dedup   │        165 │        8,251 │        - │
  │ default │        203 │       10,144 │       23 │
  └─────────┴────────────┴──────────────┴──────────┘
```

**Comment by davedoesdev** [comment] 2020-09-01 04:29
The problem is for _wildcard_ matches. The way I'm thinking of implementing these with character-based tries will require looking ahead for the next separator, which will incur a performance cost.

**Comment by davedoesdev** [comment] 2020-09-01 05:32
Also note we need to count the number of `max_words` and `max_wildcard_somes` in the topics in some way to prevent busting the stack.

**Comment by davedoesdev** [comment] 2020-09-01 07:40
The logic gets too convoluted for me :smile:

However, what does come out of this is a very decent speedup if we cache the split topics (`cache-topics` branch):

```
  add x20,000
  ┌─────────────────────┬────────────┬──────────────┬──────────┐
  │                     │ total (ms) │ average (ns) │ diff (%) │
  ├─────────────────────┼────────────┼──────────────┼──────────┤
  │ default-topic-cache │      2,603 │      130,156 │        - │
  │ default             │      6,035 │      301,773 │      132 │
  └─────────────────────┴────────────┴──────────────┴──────────┘

  match x20,000
  ┌─────────────────────┬────────────┬──────────────┬──────────┐
  │                     │ total (ms) │ average (ns) │ diff (%) │
  ├─────────────────────┼────────────┼──────────────┼──────────┤
  │ default-topic-cache │      1,254 │       62,699 │        - │
  │ default             │      2,502 │      125,106 │      100 │
  └─────────────────────┴────────────┴──────────────┴──────────┘
```

Obviously this will only apply if identical topics are used over and over again.

**Comment by mjodeh** [comment] 2020-09-01 09:17
Thanks for making the experiment, I'll get back to it in the next days

**Comment by davedoesdev** [comment] 2021-11-16 08:41
@mjodeh did you make any progress here?

**Comment by davedoesdev** [comment] 2022-05-07 06:26
No progress made, logic gets too complicated - closing

**Closed by davedoesdev** 2022-05-07 06:26 UTC
Labels: experiment
